fix: vm is undefined before vue@2.5.10
mobxjs/mobx-vue pull request #33
Opened 2019-09-11 13:00 UTC by doxiaodong

2019-09-11 14:08 UTC, kuitos requested changes

2019-09-11 14:08 UTC, kuitos commented on src/observer.ts
> +		data: (vm: Vue) => collectDataForVue(vm || this, dataDefinition),
这个 this 不对吧。。 这里是个箭头函数

2019-09-12 04:18 UTC, doxiaodong commented on src/observer.ts
> +		data: (vm: Vue) => collectDataForVue(vm || this, dataDefinition),
一会儿改一下

2019-09-12 07:23 UTC, kuitos commented on src/observer.ts
> +		data: (vm: Vue) => {
这不还是一个箭头函数么。。这个 this 指向会不对吧
应该改成
```ts
data(vm: Vue) {
  return collectDataForVue(vm || this, dataDefinition);
}
```

2019-09-12 08:42 UTC, doxiaodong commented on src/observer.ts
> +		data: (vm: Vue) => {
为什么我这里会改成这样。。心痛

2019-09-12 08:46 UTC, doxiaodong commented on src/observer.ts
> +		data: (vm: Vue) => {
你用 squash merge 吧

2019-09-12 08:53 UTC, kuitos approved these changes

2019-09-12 08:53 UTC, merged